import { useState, type FormEvent } from 'react';
import { ArrowRight } from 'lucide-react';
import type { Profile } from '../../../../../packages/shared/src/profile';
import InterestSelector from '../matching/InterestSelector';
export default function ProfilePage({ profile, onSave }: { profile: Profile; onSave: (profile: Profile) => void }) {
 const [draft, setDraft] = useState(profile);
 const [error, setError] = useState('');
 function submit(e: FormEvent) { e.preventDefault(); if (!draft.interests.length) return setError('Choose at least one interest to find your group.'); onSave({ ...draft, name: draft.name.trim(), location: draft.location.trim(), description: draft.description.trim() }); }
 return <section className="page-content profile-page"><div className="eyebrow">FIRST, A LITTLE INTRODUCTION</div><h1>What makes you, <em>you?</em></h1><p className="muted">Find your common ground before you even say hello.</p><form className="surface profile-form" onSubmit={submit}><div className="form-grid"><label>Your name<input required pattern=".*\S.*" maxLength={60} autoComplete="given-name" value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value })} placeholder="What should we call you?"/></label><label>City or neighborhood<input required pattern=".*\S.*" maxLength={100} autoComplete="address-level2" value={draft.location} onChange={e => setDraft({ ...draft, location: e.target.value })} placeholder="e.g. Vancouver, BC"/></label></div><label>A little about you<textarea maxLength={500} rows={3} placeholder="Current obsessions, weekend plans, things you’d love to try…" value={draft.description} onChange={e => setDraft({ ...draft, description: e.target.value })}/></label><fieldset><legend>What are you into?</legend><p className="field-hint">Choose a few. These help shape your group and icebreakers.</p><InterestSelector value={draft.interests} onChange={interests => { setDraft({ ...draft, interests }); setError(''); }}/></fieldset><label>Find people within {draft.radiusKm} km<input type="range" min={5} max={100} step={5} value={draft.radiusKm} onChange={e => setDraft({ ...draft, radiusKm: Number(e.target.value) })}/></label><label className="check-label"><input type="checkbox" checked={draft.transcriptionConsent} onChange={e => setDraft({ ...draft, transcriptionConsent: e.target.checked })}/><span>Allow speech transcription for event suggestions<small>Optional. Otherwise, suggestions use your interests and description. No audio is captured in this demo.</small></span></label>{error && <p role="alert" className="error">{error}</p>}<button className="primary" type="submit">Find my group<ArrowRight size={18}/></button></form></section>;
}
